/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoleRouteImport } from './routes/role'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSellerRouteImport } from './routes/onboarding.seller'
import { Route as OnboardingMapIntroRouteImport } from './routes/onboarding.map-intro'
import { Route as OnboardingManagerRouteImport } from './routes/onboarding.manager'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSellerRoute = OnboardingSellerRouteImport.update({
  id: '/onboarding/seller',
  path: '/onboarding/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMapIntroRoute = OnboardingMapIntroRouteImport.update({
  id: '/onboarding/map-intro',
  path: '/onboarding/map-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingManagerRoute = OnboardingManagerRouteImport.update({
  id: '/onboarding/manager',
  path: '/onboarding/manager',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/role'
    | '/signup'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/role'
    | '/signup'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/role'
    | '/signup'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RoleRoute: typeof RoleRoute
  SignupRoute: typeof SignupRoute
  OnboardingManagerRoute: typeof OnboardingManagerRoute
  OnboardingMapIntroRoute: typeof OnboardingMapIntroRoute
  OnboardingSellerRoute: typeof OnboardingSellerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/seller': {
      id: '/onboarding/seller'
      path: '/onboarding/seller'
      fullPath: '/onboarding/seller'
      preLoaderRoute: typeof OnboardingSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/map-intro': {
      id: '/onboarding/map-intro'
      path: '/onboarding/map-intro'
      fullPath: '/onboarding/map-intro'
      preLoaderRoute: typeof OnboardingMapIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/manager': {
      id: '/onboarding/manager'
      path: '/onboarding/manager'
      fullPath: '/onboarding/manager'
      preLoaderRoute: typeof OnboardingManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RoleRoute: RoleRoute,
  SignupRoute: SignupRoute,
  OnboardingManagerRoute: OnboardingManagerRoute,
  OnboardingMapIntroRoute: OnboardingMapIntroRoute,
  OnboardingSellerRoute: OnboardingSellerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
