/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RoleRouteImport } from './routes/role'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as MiEmpresaRouteImport } from './routes/mi-empresa'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EquipoIndexRouteImport } from './routes/equipo.index'
import { Route as OnboardingSellerRouteImport } from './routes/onboarding.seller'
import { Route as OnboardingMapIntroRouteImport } from './routes/onboarding.map-intro'
import { Route as OnboardingManagerRouteImport } from './routes/onboarding.manager'
import { Route as NodoNodeIdRouteImport } from './routes/nodo.$nodeId'
import { Route as EquipoSellerIdRouteImport } from './routes/equipo.$sellerId'
import { Route as NodoNodeIdQuizRouteImport } from './routes/nodo.$nodeId.quiz'
import { Route as NodoNodeIdPracticaRouteImport } from './routes/nodo.$nodeId.practica'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const MiEmpresaRoute = MiEmpresaRouteImport.update({
  id: '/mi-empresa',
  path: '/mi-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoIndexRoute = EquipoIndexRouteImport.update({
  id: '/equipo/',
  path: '/equipo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSellerRoute = OnboardingSellerRouteImport.update({
  id: '/onboarding/seller',
  path: '/onboarding/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingMapIntroRoute = OnboardingMapIntroRouteImport.update({
  id: '/onboarding/map-intro',
  path: '/onboarding/map-intro',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingManagerRoute = OnboardingManagerRouteImport.update({
  id: '/onboarding/manager',
  path: '/onboarding/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const NodoNodeIdRoute = NodoNodeIdRouteImport.update({
  id: '/nodo/$nodeId',
  path: '/nodo/$nodeId',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoSellerIdRoute = EquipoSellerIdRouteImport.update({
  id: '/equipo/$sellerId',
  path: '/equipo/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const NodoNodeIdQuizRoute = NodoNodeIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => NodoNodeIdRoute,
} as any)
const NodoNodeIdPracticaRoute = NodoNodeIdPracticaRouteImport.update({
  id: '/practica',
  path: '/practica',
  getParentRoute: () => NodoNodeIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mi-empresa': typeof MiEmpresaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/equipo/$sellerId': typeof EquipoSellerIdRoute
  '/nodo/$nodeId': typeof NodoNodeIdRouteWithChildren
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
  '/equipo/': typeof EquipoIndexRoute
  '/nodo/$nodeId/practica': typeof NodoNodeIdPracticaRoute
  '/nodo/$nodeId/quiz': typeof NodoNodeIdQuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mi-empresa': typeof MiEmpresaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/equipo/$sellerId': typeof EquipoSellerIdRoute
  '/nodo/$nodeId': typeof NodoNodeIdRouteWithChildren
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
  '/equipo': typeof EquipoIndexRoute
  '/nodo/$nodeId/practica': typeof NodoNodeIdPracticaRoute
  '/nodo/$nodeId/quiz': typeof NodoNodeIdQuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/mi-empresa': typeof MiEmpresaRoute
  '/reset-password': typeof ResetPasswordRoute
  '/role': typeof RoleRoute
  '/signup': typeof SignupRoute
  '/equipo/$sellerId': typeof EquipoSellerIdRoute
  '/nodo/$nodeId': typeof NodoNodeIdRouteWithChildren
  '/onboarding/manager': typeof OnboardingManagerRoute
  '/onboarding/map-intro': typeof OnboardingMapIntroRoute
  '/onboarding/seller': typeof OnboardingSellerRoute
  '/equipo/': typeof EquipoIndexRoute
  '/nodo/$nodeId/practica': typeof NodoNodeIdPracticaRoute
  '/nodo/$nodeId/quiz': typeof NodoNodeIdQuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/mi-empresa'
    | '/reset-password'
    | '/role'
    | '/signup'
    | '/equipo/$sellerId'
    | '/nodo/$nodeId'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
    | '/equipo/'
    | '/nodo/$nodeId/practica'
    | '/nodo/$nodeId/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/mi-empresa'
    | '/reset-password'
    | '/role'
    | '/signup'
    | '/equipo/$sellerId'
    | '/nodo/$nodeId'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
    | '/equipo'
    | '/nodo/$nodeId/practica'
    | '/nodo/$nodeId/quiz'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/mapa'
    | '/mi-empresa'
    | '/reset-password'
    | '/role'
    | '/signup'
    | '/equipo/$sellerId'
    | '/nodo/$nodeId'
    | '/onboarding/manager'
    | '/onboarding/map-intro'
    | '/onboarding/seller'
    | '/equipo/'
    | '/nodo/$nodeId/practica'
    | '/nodo/$nodeId/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MiEmpresaRoute: typeof MiEmpresaRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoleRoute: typeof RoleRoute
  SignupRoute: typeof SignupRoute
  EquipoSellerIdRoute: typeof EquipoSellerIdRoute
  NodoNodeIdRoute: typeof NodoNodeIdRouteWithChildren
  OnboardingManagerRoute: typeof OnboardingManagerRoute
  OnboardingMapIntroRoute: typeof OnboardingMapIntroRoute
  OnboardingSellerRoute: typeof OnboardingSellerRoute
  EquipoIndexRoute: typeof EquipoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-empresa': {
      id: '/mi-empresa'
      path: '/mi-empresa'
      fullPath: '/mi-empresa'
      preLoaderRoute: typeof MiEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/': {
      id: '/equipo/'
      path: '/equipo'
      fullPath: '/equipo/'
      preLoaderRoute: typeof EquipoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/seller': {
      id: '/onboarding/seller'
      path: '/onboarding/seller'
      fullPath: '/onboarding/seller'
      preLoaderRoute: typeof OnboardingSellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/map-intro': {
      id: '/onboarding/map-intro'
      path: '/onboarding/map-intro'
      fullPath: '/onboarding/map-intro'
      preLoaderRoute: typeof OnboardingMapIntroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/manager': {
      id: '/onboarding/manager'
      path: '/onboarding/manager'
      fullPath: '/onboarding/manager'
      preLoaderRoute: typeof OnboardingManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodo/$nodeId': {
      id: '/nodo/$nodeId'
      path: '/nodo/$nodeId'
      fullPath: '/nodo/$nodeId'
      preLoaderRoute: typeof NodoNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo/$sellerId': {
      id: '/equipo/$sellerId'
      path: '/equipo/$sellerId'
      fullPath: '/equipo/$sellerId'
      preLoaderRoute: typeof EquipoSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nodo/$nodeId/quiz': {
      id: '/nodo/$nodeId/quiz'
      path: '/quiz'
      fullPath: '/nodo/$nodeId/quiz'
      preLoaderRoute: typeof NodoNodeIdQuizRouteImport
      parentRoute: typeof NodoNodeIdRoute
    }
    '/nodo/$nodeId/practica': {
      id: '/nodo/$nodeId/practica'
      path: '/practica'
      fullPath: '/nodo/$nodeId/practica'
      preLoaderRoute: typeof NodoNodeIdPracticaRouteImport
      parentRoute: typeof NodoNodeIdRoute
    }
  }
}

interface NodoNodeIdRouteChildren {
  NodoNodeIdPracticaRoute: typeof NodoNodeIdPracticaRoute
  NodoNodeIdQuizRoute: typeof NodoNodeIdQuizRoute
}

const NodoNodeIdRouteChildren: NodoNodeIdRouteChildren = {
  NodoNodeIdPracticaRoute: NodoNodeIdPracticaRoute,
  NodoNodeIdQuizRoute: NodoNodeIdQuizRoute,
}

const NodoNodeIdRouteWithChildren = NodoNodeIdRoute._addFileChildren(
  NodoNodeIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MiEmpresaRoute: MiEmpresaRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoleRoute: RoleRoute,
  SignupRoute: SignupRoute,
  EquipoSellerIdRoute: EquipoSellerIdRoute,
  NodoNodeIdRoute: NodoNodeIdRouteWithChildren,
  OnboardingManagerRoute: OnboardingManagerRoute,
  OnboardingMapIntroRoute: OnboardingMapIntroRoute,
  OnboardingSellerRoute: OnboardingSellerRoute,
  EquipoIndexRoute: EquipoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
